//! Raw FFI bindings for libjq.
//!
//! This module provides `#[repr(C)]` type definitions that mirror jq's internal
//! C structures, plus `extern "C"` declarations for the public API functions we need.
//!
//! # Safety
//!
//! All types and functions in this module are `unsafe` by nature.  They should only
//! be used through the safe wrappers in `crate::bytecode`.
//!
//! # Layout notes
//!
//! - `jv` is a 16-byte tagged union (jv.h).  We treat it as opaque and access it
//!   only via the `jv_*` FFI functions.
//! - `struct bytecode` is defined in jq's internal `bytecode.h`.  Since it is not
//!   in the public header, we provide a hand-written `#[repr(C)]` definition that
//!   must match jq 1.8.1 exactly.
//! - `jq_state` is opaque.  We extract the `bytecode*` field by computing its
//!   offset within the struct (see `jq_state_get_bytecode`).

use std::ffi::c_char;
use std::ffi::c_int;

// ---------------------------------------------------------------------------
// jv type (jv.h)
// ---------------------------------------------------------------------------

/// jq value kind tags (from jv.h `jv_kind` enum).
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JvKind {
    Invalid = 0,
    Null = 1,
    False = 2,
    True = 3,
    Number = 4,
    String = 5,
    Array = 6,
    Object = 7,
}

/// Opaque reference-counted pointer used inside `jv`.
#[repr(C)]
pub struct JvRefcnt {
    _opaque: [u8; 0],
}

/// The `jv` tagged union.  16 bytes on all 64-bit platforms.
///
/// ```c
/// typedef struct {
///   unsigned char kind_flags;
///   unsigned char pad_;
///   unsigned short offset;
///   int size;
///   union { struct jv_refcnt* ptr; double number; } u;
/// } jv;
/// ```
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Jv {
    pub kind_flags: u8,
    pub pad_: u8,
    pub offset: u16,
    pub size: i32,
    pub u: JvPayload,
}

/// Payload union of `jv`: either a heap pointer or an inline double.
#[repr(C)]
#[derive(Clone, Copy)]
pub union JvPayload {
    pub ptr: *mut JvRefcnt,
    pub number: f64,
}

// Verify that jv is exactly 16 bytes (compile-time assertion).
const _: () = assert!(std::mem::size_of::<Jv>() == 16);

// ---------------------------------------------------------------------------
// Opcode enum (opcode_list.h)
// ---------------------------------------------------------------------------

/// jq bytecode opcodes.
///
/// The order matches `opcode_list.h` in jq 1.8.1 exactly, since the C enum is
/// generated by sequential macro expansion.
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(non_camel_case_types)]
pub enum Opcode {
    LOADK = 0,
    DUP = 1,
    DUPN = 2,
    DUP2 = 3,
    PUSHK_UNDER = 4,
    POP = 5,
    LOADV = 6,
    LOADVN = 7,
    STOREV = 8,
    STORE_GLOBAL = 9,
    INDEX = 10,
    INDEX_OPT = 11,
    EACH = 12,
    EACH_OPT = 13,
    FORK = 14,
    TRY_BEGIN = 15,
    TRY_END = 16,
    JUMP = 17,
    JUMP_F = 18,
    BACKTRACK = 19,
    APPEND = 20,
    INSERT = 21,
    RANGE = 22,
    SUBEXP_BEGIN = 23,
    SUBEXP_END = 24,
    PATH_BEGIN = 25,
    PATH_END = 26,
    CALL_BUILTIN = 27,
    CALL_JQ = 28,
    RET = 29,
    TAIL_CALL_JQ = 30,
    CLOSURE_PARAM = 31,
    CLOSURE_REF = 32,
    CLOSURE_CREATE = 33,
    CLOSURE_CREATE_C = 34,
    TOP = 35,
    CLOSURE_PARAM_REGULAR = 36,
    DEPS = 37,
    MODULEMETA = 38,
    GENLABEL = 39,
    DESTRUCTURE_ALT = 40,
    STOREVN = 41,
    ERRORK = 42,
}

impl Opcode {
    /// Try to convert a raw u16 into an Opcode.
    pub fn from_u16(v: u16) -> Option<Self> {
        if v <= 42 {
            // SAFETY: all values 0..=42 are valid enum variants.
            Some(unsafe { std::mem::transmute(v) })
        } else {
            None
        }
    }

    /// Human-readable name matching jq's output.
    pub fn name(self) -> &'static str {
        match self {
            Self::LOADK => "LOADK",
            Self::DUP => "DUP",
            Self::DUPN => "DUPN",
            Self::DUP2 => "DUP2",
            Self::PUSHK_UNDER => "PUSHK_UNDER",
            Self::POP => "POP",
            Self::LOADV => "LOADV",
            Self::LOADVN => "LOADVN",
            Self::STOREV => "STOREV",
            Self::STORE_GLOBAL => "STORE_GLOBAL",
            Self::INDEX => "INDEX",
            Self::INDEX_OPT => "INDEX_OPT",
            Self::EACH => "EACH",
            Self::EACH_OPT => "EACH_OPT",
            Self::FORK => "FORK",
            Self::TRY_BEGIN => "TRY_BEGIN",
            Self::TRY_END => "TRY_END",
            Self::JUMP => "JUMP",
            Self::JUMP_F => "JUMP_F",
            Self::BACKTRACK => "BACKTRACK",
            Self::APPEND => "APPEND",
            Self::INSERT => "INSERT",
            Self::RANGE => "RANGE",
            Self::SUBEXP_BEGIN => "SUBEXP_BEGIN",
            Self::SUBEXP_END => "SUBEXP_END",
            Self::PATH_BEGIN => "PATH_BEGIN",
            Self::PATH_END => "PATH_END",
            Self::CALL_BUILTIN => "CALL_BUILTIN",
            Self::CALL_JQ => "CALL_JQ",
            Self::RET => "RET",
            Self::TAIL_CALL_JQ => "TAIL_CALL_JQ",
            Self::CLOSURE_PARAM => "CLOSURE_PARAM",
            Self::CLOSURE_REF => "CLOSURE_REF",
            Self::CLOSURE_CREATE => "CLOSURE_CREATE",
            Self::CLOSURE_CREATE_C => "CLOSURE_CREATE_C",
            Self::TOP => "TOP",
            Self::CLOSURE_PARAM_REGULAR => "CLOSURE_PARAM_REGULAR",
            Self::DEPS => "DEPS",
            Self::MODULEMETA => "MODULEMETA",
            Self::GENLABEL => "GENLABEL",
            Self::DESTRUCTURE_ALT => "DESTRUCTURE_ALT",
            Self::STOREVN => "STOREVN",
            Self::ERRORK => "ERRORK",
        }
    }
}

// ---------------------------------------------------------------------------
// Opcode flags (bytecode.h)
// ---------------------------------------------------------------------------

pub const OP_HAS_CONSTANT: u32 = 2;
pub const OP_HAS_VARIABLE: u32 = 4;
pub const OP_HAS_BRANCH: u32 = 8;
pub const OP_HAS_CFUNC: u32 = 32;
pub const OP_HAS_UFUNC: u32 = 64;
pub const OP_IS_CALL_PSEUDO: u32 = 128;
pub const OP_HAS_BINDING: u32 = 1024;

// ---------------------------------------------------------------------------
// struct bytecode (bytecode.h)
// ---------------------------------------------------------------------------

/// C function pointer union — we only need the raw pointer for identification.
#[repr(C)]
pub union CFunctionPtr {
    pub a1: unsafe extern "C" fn(*mut JqState, Jv) -> Jv,
    pub a2: unsafe extern "C" fn(*mut JqState, Jv, Jv) -> Jv,
    pub a3: unsafe extern "C" fn(*mut JqState, Jv, Jv, Jv) -> Jv,
    pub a4: unsafe extern "C" fn(*mut JqState, Jv, Jv, Jv, Jv) -> Jv,
}

/// `struct cfunction` from bytecode.h.
#[repr(C)]
pub struct CFunction {
    pub fptr: CFunctionPtr,
    pub name: *const c_char,
    pub nargs: c_int,
}

/// `struct symbol_table` from bytecode.h.
#[repr(C)]
pub struct SymbolTable {
    pub cfunctions: *mut CFunction,
    pub ncfunctions: c_int,
    pub cfunc_names: Jv, // 16 bytes
}

/// `struct bytecode` from bytecode.h (jq 1.8.1).
///
/// This must have the exact same memory layout as the C struct.
#[repr(C)]
pub struct Bytecode {
    pub code: *mut u16,
    pub codelen: c_int,
    pub nlocals: c_int,
    pub nclosures: c_int,
    // 4 bytes padding here (to align `constants` to 8 bytes)
    pub constants: Jv, // 16 bytes
    pub globals: *mut SymbolTable,
    pub subfunctions: *mut *mut Bytecode,
    pub nsubfunctions: c_int,
    // 4 bytes padding here (to align `parent` to 8 bytes)
    pub parent: *mut Bytecode,
    pub debuginfo: Jv, // 16 bytes
}

// ---------------------------------------------------------------------------
// jq_state — opaque, accessed via offset
// ---------------------------------------------------------------------------

/// Opaque `jq_state` handle.  We never construct this directly.
#[repr(C)]
pub struct JqState {
    _opaque: [u8; 0],
}

/// Offset of the `bc` field within `struct jq_state`.
///
/// ```c
/// struct jq_state {
///   void (*nomem_handler)(void *);   // 0: 8 bytes (fn ptr)
///   void *nomem_handler_data;        // 8: 8 bytes (ptr)
///   struct bytecode* bc;             // 16: 8 bytes (ptr)  <-- this
///   ...
/// };
/// ```
const JQ_STATE_BC_OFFSET: usize = 16;

/// Extract the `struct bytecode*` from a `jq_state*`.
///
/// # Safety
///
/// `state` must be a valid, non-null pointer returned by `jq_init()` after a
/// successful `jq_compile()` call.
pub unsafe fn jq_state_get_bytecode(state: *mut JqState) -> *mut Bytecode {
    unsafe {
        let base = state as *const u8;
        let bc_ptr_location = base.add(JQ_STATE_BC_OFFSET) as *const *mut Bytecode;
        *bc_ptr_location
    }
}

// ---------------------------------------------------------------------------
// libjq public API (jq.h + jv.h)
// ---------------------------------------------------------------------------

unsafe extern "C" {
    // jq lifecycle
    pub fn jq_init() -> *mut JqState;
    pub fn jq_compile(state: *mut JqState, program: *const c_char) -> c_int;
    pub fn jq_teardown(state: *mut *mut JqState);

    // jq execution
    pub fn jq_start(state: *mut JqState, value: Jv, flags: c_int);
    pub fn jq_next(state: *mut JqState) -> Jv;

    // jq debug
    pub fn jq_dump_disassembly(state: *mut JqState, indent: c_int);

    // jv constructors
    pub fn jv_null() -> Jv;
    pub fn jv_number(n: f64) -> Jv;
    pub fn jv_string(s: *const c_char) -> Jv;
    pub fn jv_array() -> Jv;

    // jv accessors
    pub fn jv_get_kind(v: Jv) -> JvKind;
    pub fn jv_number_value(v: Jv) -> f64;
    pub fn jv_string_value(v: Jv) -> *const c_char;
    pub fn jv_string_length_bytes(v: Jv) -> c_int;
    pub fn jv_array_length(v: Jv) -> c_int;
    pub fn jv_array_get(arr: Jv, idx: c_int) -> Jv;

    // jv reference counting
    pub fn jv_copy(v: Jv) -> Jv;
    pub fn jv_free(v: Jv);

    // jv predicates
    pub fn jv_is_valid(v: Jv) -> c_int;

    // jv error handling
    pub fn jv_invalid_get_msg(v: Jv) -> Jv;

    // jv parsing
    pub fn jv_parse(s: *const c_char) -> Jv;

    // jv object iteration
    pub fn jv_object_iter(v: Jv) -> c_int;
    pub fn jv_object_iter_next(v: Jv, iter: c_int) -> c_int;
    pub fn jv_object_iter_valid(v: Jv, iter: c_int) -> c_int;
    pub fn jv_object_iter_key(v: Jv, iter: c_int) -> Jv;
    pub fn jv_object_iter_value(v: Jv, iter: c_int) -> Jv;

    // jv display
    pub fn jv_dump_string(v: Jv, flags: c_int) -> Jv;

    // jv object access
    pub fn jv_object_get(obj: Jv, key: Jv) -> Jv;
}

// ---------------------------------------------------------------------------
// Opcode immediate type helpers
// ---------------------------------------------------------------------------

/// Per-opcode metadata: (flags, base_length) pairs.
///
/// Derived directly from the C macro definitions in bytecode.c:
///
/// ```c
/// #define NONE 0, 1
/// #define CONSTANT OP_HAS_CONSTANT, 2
/// #define VARIABLE (OP_HAS_VARIABLE | OP_HAS_BINDING), 3
/// #define GLOBAL   (OP_HAS_CONSTANT | OP_HAS_VARIABLE | OP_HAS_BINDING | OP_IS_CALL_PSEUDO), 4
/// #define BRANCH   OP_HAS_BRANCH, 2
/// #define CFUNC    (OP_HAS_CFUNC | OP_HAS_BINDING), 3
/// #define UFUNC    (OP_HAS_UFUNC | OP_HAS_BINDING | OP_IS_CALL_PSEUDO), 4
/// #define DEFINITION (OP_IS_CALL_PSEUDO | OP_HAS_BINDING), 0
/// #define CLOSURE_REF_IMM (OP_IS_CALL_PSEUDO | OP_HAS_BINDING), 2
/// ```
fn opcode_meta(op: Opcode) -> (u32, usize) {
    // Returns (flags, base_length) matching the C opcode_descriptions table.
    //
    // Note: CALL_JQ/TAIL_CALL_JQ have variable length: base + code[pc+1]*2
    // (handled by opcode_length_with_code).
    match op {
        // NONE -> (0, 1)
        Opcode::DUP => (0, 1),
        Opcode::DUPN => (0, 1),
        Opcode::DUP2 => (0, 1),
        Opcode::POP => (0, 1),
        Opcode::INDEX => (0, 1),
        Opcode::INDEX_OPT => (0, 1),
        Opcode::EACH => (0, 1),
        Opcode::EACH_OPT => (0, 1),
        Opcode::TRY_END => (0, 1),
        Opcode::BACKTRACK => (0, 1),
        Opcode::INSERT => (0, 1),
        Opcode::SUBEXP_BEGIN => (0, 1),
        Opcode::SUBEXP_END => (0, 1),
        Opcode::PATH_BEGIN => (0, 1),
        Opcode::PATH_END => (0, 1),
        Opcode::RET => (0, 1),
        Opcode::TOP => (0, 1),
        Opcode::GENLABEL => (0, 1),

        // CONSTANT -> (OP_HAS_CONSTANT, 2)
        Opcode::LOADK => (OP_HAS_CONSTANT, 2),
        Opcode::PUSHK_UNDER => (OP_HAS_CONSTANT, 2),
        Opcode::DEPS => (OP_HAS_CONSTANT, 2),
        Opcode::MODULEMETA => (OP_HAS_CONSTANT, 2),
        Opcode::ERRORK => (OP_HAS_CONSTANT, 2),

        // VARIABLE -> (OP_HAS_VARIABLE | OP_HAS_BINDING, 3)
        Opcode::LOADV => (OP_HAS_VARIABLE | OP_HAS_BINDING, 3),
        Opcode::LOADVN => (OP_HAS_VARIABLE | OP_HAS_BINDING, 3),
        Opcode::STOREV => (OP_HAS_VARIABLE | OP_HAS_BINDING, 3),
        Opcode::APPEND => (OP_HAS_VARIABLE | OP_HAS_BINDING, 3),
        Opcode::RANGE => (OP_HAS_VARIABLE | OP_HAS_BINDING, 3),
        Opcode::STOREVN => (OP_HAS_VARIABLE | OP_HAS_BINDING, 3),

        // GLOBAL -> (OP_HAS_CONSTANT | OP_HAS_VARIABLE | OP_HAS_BINDING | OP_IS_CALL_PSEUDO, 4)
        Opcode::STORE_GLOBAL => (
            OP_HAS_CONSTANT | OP_HAS_VARIABLE | OP_HAS_BINDING | OP_IS_CALL_PSEUDO,
            4,
        ),

        // BRANCH -> (OP_HAS_BRANCH, 2)
        Opcode::FORK => (OP_HAS_BRANCH, 2),
        Opcode::TRY_BEGIN => (OP_HAS_BRANCH, 2),
        Opcode::JUMP => (OP_HAS_BRANCH, 2),
        Opcode::JUMP_F => (OP_HAS_BRANCH, 2),
        Opcode::DESTRUCTURE_ALT => (OP_HAS_BRANCH, 2),

        // CFUNC -> (OP_HAS_CFUNC | OP_HAS_BINDING, 3)
        Opcode::CALL_BUILTIN => (OP_HAS_CFUNC | OP_HAS_BINDING, 3),

        // UFUNC -> (OP_HAS_UFUNC | OP_HAS_BINDING | OP_IS_CALL_PSEUDO, 4)
        Opcode::CALL_JQ => (OP_HAS_UFUNC | OP_HAS_BINDING | OP_IS_CALL_PSEUDO, 4),
        Opcode::TAIL_CALL_JQ => (OP_HAS_UFUNC | OP_HAS_BINDING | OP_IS_CALL_PSEUDO, 4),

        // DEFINITION -> (OP_IS_CALL_PSEUDO | OP_HAS_BINDING, 0)
        // These pseudo-instructions have length 0 in the description table,
        // but they don't appear independently in the bytecode stream.
        // They are part of CALL_JQ's variable-length encoding.
        Opcode::CLOSURE_PARAM => (OP_IS_CALL_PSEUDO | OP_HAS_BINDING, 0),
        Opcode::CLOSURE_CREATE => (OP_IS_CALL_PSEUDO | OP_HAS_BINDING, 0),
        Opcode::CLOSURE_CREATE_C => (OP_IS_CALL_PSEUDO | OP_HAS_BINDING, 0),
        Opcode::CLOSURE_PARAM_REGULAR => (OP_IS_CALL_PSEUDO | OP_HAS_BINDING, 0),

        // CLOSURE_REF_IMM -> (OP_IS_CALL_PSEUDO | OP_HAS_BINDING, 2)
        Opcode::CLOSURE_REF => (OP_IS_CALL_PSEUDO | OP_HAS_BINDING, 2),
    }
}

/// Opcode flags for each opcode (mirrors opcode_describe()->flags).
pub fn opcode_flags(op: Opcode) -> u32 {
    opcode_meta(op).0
}

/// Base instruction length (in 16-bit words), NOT including CALL_JQ's variable part.
///
/// For CALL_JQ and TAIL_CALL_JQ, the actual length depends on the first immediate
/// (nargs): `base_length + code[pc+1] * 2`.  Use [`opcode_length_with_code`] instead.
pub fn opcode_base_length(op: Opcode) -> usize {
    opcode_meta(op).1
}

/// Instruction length including variable-length CALL_JQ encoding.
///
/// `code` is the slice starting at the opcode word.
pub fn opcode_length_with_code(op: Opcode, code: &[u16]) -> usize {
    let base = opcode_base_length(op);
    if (op == Opcode::CALL_JQ || op == Opcode::TAIL_CALL_JQ) && code.len() > 1 {
        // code[1] = nargs; each arg takes 2 words (level + idx)
        let nargs = code[1] as usize;
        base + nargs * 2
    } else {
        base
    }
}
